"""Anomaly detector module for Automated Anomaly Explanation with Counterfactuals.

Provides a clean, deterministic Isolation Forest wrapper.
Expects pre-scaled, validated features containing only the approved detector inputs.
"""

from pathlib import Path
from typing import Optional

import pandas as pd
import yaml
import joblib
from sklearn.ensemble import IsolationForest

# Resolve project root relative to this file
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_FEATURES_CONFIG = PROJECT_ROOT / "config" / "features.yaml"
DEFAULT_MODEL_CONFIG = PROJECT_ROOT / "config" / "model_config.yaml"


class AnomalyDetector:
    """Deterministic Isolation Forest wrapper for anomaly detection.

    Expects strictly scaled, normal-only training data during fit.
    Maintains stateless prediction behaviour for the counterfactual engine.
    """

    def __init__(
        self,
        features_config_path: Optional[Path] = None,
        model_config_path: Optional[Path] = None,
    ):
        """Initialize the anomaly detector using configurations.

        Parameters
        ----------
        features_config_path : Optional[Path]
            Path to features.yaml configuration file.
        model_config_path : Optional[Path]
            Path to model_config.yaml configuration file.
        """
        self.features_config_path = features_config_path or DEFAULT_FEATURES_CONFIG
        self.model_config_path = model_config_path or DEFAULT_MODEL_CONFIG

        # Load configurations
        with open(self.features_config_path, "r") as f:
            self.features_config = yaml.safe_load(f)

        with open(self.model_config_path, "r") as f:
            self.model_config = yaml.safe_load(f)

        self.feature_names = self.features_config["feature_sets"]["detector_inputs"]
        self.detector_config = self.model_config["detector"]["parameters"]
        
        self.normal_label = self.model_config["detector"]["prediction_mapping"]["normal_value"]
        self.anomaly_label = self.model_config["detector"]["prediction_mapping"]["anomaly_value"]

        # Initialize the underlying scikit-learn model
        self.model = IsolationForest(**self.detector_config)
        self.is_fitted = False

    def _validate_input(self, df: pd.DataFrame) -> None:
        """Validate input features before fitting or predicting.

        Parameters
        ----------
        df : pd.DataFrame
            The input dataframe containing scaled features.

        Raises
        ------
        ValueError
            If the input fails any strict validation checks.
        """
        if not isinstance(df, pd.DataFrame):
            raise ValueError("Input must be a pandas DataFrame.")

        if df.empty:
            raise ValueError("Input DataFrame is empty.")

        if df.columns.duplicated().any():
            raise ValueError("Input DataFrame contains duplicate column names.")

        if df.isnull().values.any():
            raise ValueError("Input DataFrame contains missing values.")

        if list(df.columns) != self.feature_names:
            raise ValueError(
                f"Input columns do not exactly match approved features.\n"
                f"Expected: {self.feature_names}\n"
                f"Received: {list(df.columns)}"
            )

        # Check that all columns are numeric
        for col in df.columns:
            if not pd.api.types.is_numeric_dtype(df[col]):
                raise ValueError(f"Column '{col}' is not numeric.")

    def fit(self, scaled_normal_training_features: pd.DataFrame) -> "AnomalyDetector":
        """Fit the Isolation Forest model.

        Parameters
        ----------
        scaled_normal_training_features : pd.DataFrame
            The scaled normal-training features generated by the preprocessing module.

        Returns
        -------
        AnomalyDetector
            The fitted detector instance.
        """
        self._validate_input(scaled_normal_training_features)
        
        self.model.fit(scaled_normal_training_features)
        self.is_fitted = True
        return self

    def predict_anomaly_score(self, scaled_features: pd.DataFrame) -> pd.Series:
        """Predict the anomaly score using the decision function.

        Higher scores indicate more normal observations.
        Lower scores indicate more anomalous observations.

        Parameters
        ----------
        scaled_features : pd.DataFrame
            The scaled input features to score.

        Returns
        -------
        pd.Series
            A Series containing anomaly scores, preserving the input index.

        Raises
        ------
        RuntimeError
            If the detector has not been fitted.
        """
        if not self.is_fitted:
            raise RuntimeError("Cannot predict scores with an unfitted detector.")
            
        self._validate_input(scaled_features)

        scores = self.model.decision_function(scaled_features)
        return pd.Series(scores, index=scaled_features.index, name="anomaly_score")

    def predict_labels(self, scaled_features: pd.DataFrame) -> pd.Series:
        """Predict normal/anomaly labels based on the initial contamination threshold.

        Labels map strictly to 1 (NORMAL) and -1 (ANOMALY) as configured.

        Parameters
        ----------
        scaled_features : pd.DataFrame
            The scaled input features to classify.

        Returns
        -------
        pd.Series
            A Series containing predicted labels, preserving the input index.

        Raises
        ------
        RuntimeError
            If the detector has not been fitted.
        """
        if not self.is_fitted:
            raise RuntimeError("Cannot predict labels with an unfitted detector.")
            
        self._validate_input(scaled_features)

        labels = self.model.predict(scaled_features)
        return pd.Series(labels, index=scaled_features.index, name="predicted_label")

    def is_anomaly(self, scaled_features: pd.DataFrame) -> pd.Series:
        """Return a boolean mask indicating which observations are anomalous.

        True = ANOMALY
        False = NORMAL

        Parameters
        ----------
        scaled_features : pd.DataFrame
            The scaled input features to evaluate.

        Returns
        -------
        pd.Series
            A boolean Series, preserving the input index.

        Raises
        ------
        RuntimeError
            If the detector has not been fitted.
        """
        labels = self.predict_labels(scaled_features)
        return labels == self.anomaly_label

    def save(self, path: Optional[Path] = None) -> None:
        """Save the fitted detector artifact to disk.

        Parameters
        ----------
        path : Optional[Path]
            Custom path. If None, uses the artifact path defined in model_config.yaml.

        Raises
        ------
        RuntimeError
            If the detector has not been fitted.
        """
        if not self.is_fitted:
            raise RuntimeError("Cannot save an unfitted detector.")

        if path is None:
            relative_path = self.model_config["artifacts"]["model_path"]
            path = PROJECT_ROOT / relative_path
        else:
            path = Path(path)

        path.parent.mkdir(parents=True, exist_ok=True)

        artifact = {
            "model": self.model,
            "feature_names": self.feature_names,
            "normal_label": self.normal_label,
            "anomaly_label": self.anomaly_label,
        }
        joblib.dump(artifact, path)

    @classmethod
    def load(
        cls,
        path: Optional[Path] = None,
        features_config_path: Optional[Path] = None,
        model_config_path: Optional[Path] = None,
    ) -> "AnomalyDetector":
        """Load a fitted detector from an artifact.

        Validates that the artifact feature names strictly match the current
        approved configuration policies before returning.

        Parameters
        ----------
        path : Optional[Path]
            Path to the saved detector artifact. If None, uses the
            artifact path defined in model_config.yaml.
        features_config_path : Optional[Path]
            Path to features.yaml configuration file.
        model_config_path : Optional[Path]
            Path to model_config.yaml configuration file.

        Returns
        -------
        AnomalyDetector
            A ready-to-predict detector instance.

        Raises
        ------
        ValueError
            If artifact feature names do not match configuration feature names.
        """
        instance = cls(features_config_path, model_config_path)

        if path is None:
            relative_path = instance.model_config["artifacts"]["model_path"]
            path = PROJECT_ROOT / relative_path
        else:
            path = Path(path)

        artifact = joblib.load(path)
        
        # Security/Consistency validation
        if instance.feature_names != artifact["feature_names"]:
            raise ValueError(
                f"Feature mismatch between artifact and current config.\n"
                f"Artifact features: {artifact['feature_names']}\n"
                f"Config features:   {instance.feature_names}"
            )

        instance.model = artifact["model"]
        instance.is_fitted = True
        return instance
